package com.genir.renderer.loaders;

import java.util.Arrays;
import java.util.List;

import static com.genir.renderer.loaders.ClassConstantTransformer.newTransform;

/** macOS obfuscation mapping table. Drop-in replacement for ObfTransformations. */
public class ObfTransformations {
    public static List<ClassConstantTransformer.Transform> transformations = Arrays.asList(
            newTransform("proxy/com/fs/graphics/particle/DynamicParticleGroup", "com/fs/graphics/particle/DynamicParticleGroup"),
            newTransform("proxy/com/fs/graphics/LayeredRenderable", "com/fs/graphics/LayeredRenderable"),
            newTransform("proxy/com/fs/graphics/Sprite", "com/fs/graphics/Sprite"),
            newTransform("proxy/com/fs/starfarer/combat/entities/CustomCombatEntity", "com/fs/starfarer/combat/entities/CustomCombatEntity"),
            newTransform("proxy/com/fs/starfarer/combat/CombatViewport", "com/fs/starfarer/combat/CombatViewport"),
            newTransform("proxy/com/fs/starfarer/loading/scripts/ScriptStore", "com/fs/starfarer/loading/scripts/ScriptStore"),
            newTransform("proxy/com/fs/starfarer/loading/specs/BaseWeaponSpec", "com/fs/starfarer/loading/specs/BaseWeaponSpec"),
            newTransform("proxy/com/fs/starfarer/renderers/damage/DebrisParticleSystem", "com/fs/starfarer/renderers/damage/DebrisParticleSystem"),
            newTransform("proxy/com/fs/starfarer/renderers/damage/ExplosionParticleSystem", "com/fs/starfarer/renderers/damage/ExplosionParticleSystem"),
            newTransform("proxy/com/fs/starfarer/settings/StarfarerSettings", "com/fs/starfarer/settings/StarfarerSettings"),
            newTransform("proxy/com/fs/util/container/repo/ObjectRepository", "com/fs/util/container/repo/ObjectRepository"),
            newTransform("proxy/sound/Sound", "sound/Sound"),
            newTransform("proxy/com/fs/starfarer/loading/ResourceLoaderState", "com/fs/starfarer/loading/ResourceLoaderState"),
            newTransform("proxy/com/fs/starfarer/loading/SpecStore", "com/fs/starfarer/loading/SpecStore"),
            newTransform("proxy/com/fs/util/container/Pair", "com/fs/util/container/Pair"),
            newTransform("proxy/com/fs/starfarer/campaign/fleet/FleetMember", "com/fs/starfarer/campaign/fleet/FleetMember"),
            newTransform("proxy/com/fs/graphics/FileRepository", "com/fs/graphics/L"),
            newTransform("proxy/com/fs/graphics/TextureRepository", "com/fs/graphics/void"),
            newTransform("proxy/com/fs/graphics/AlphaAdder", "com/fs/graphics/oO0O"),
            newTransform("proxy/com/fs/graphics/font/FontRepository", "com/fs/graphics/A/String"),
            newTransform("proxy/com/fs/starfarer/loading/scripts/SecureClassLoader", "com/fs/starfarer/loading/scripts/OoOO"),
            newTransform("proxy/com/fs/starfarer/loading/JavaSourceFinder", "com/fs/starfarer/loading/U"),
            newTransform("proxy/com/fs/starfarer/loading/specs/ShipHullSpec", "com/fs/starfarer/loading/specs/g"),
            newTransform("proxy/com/fs/util/ResourceLoader$ResourceLocationType", "com/fs/util/C$o"),
            newTransform("proxy/com/fs/util/ResourceLoader$ResourceLocation", "com/fs/util/C$Oo"),
            newTransform("proxy/com/fs/util/ResourceLoader", "com/fs/util/C"),
            newTransform("proxy/com/fs/starfarer/renderers/FloatingTextManager", "com/fs/starfarer/renderers/interface"),
            newTransform("proxy/com/fs/starfarer/campaign/save/ProgressBar", "com/fs/starfarer/campaign/save/new"),
            newTransform("proxy/com/fs/graphics/TextureHandler", "com/fs/graphics/Object"),
            newTransform("proxy/com/fs/graphics/TextureTransformer", "com/fs/graphics/oooO"),
            newTransform("proxy/com/fs/starfarer/combat/ai/admiral/DeploymentManager", "com/fs/starfarer/combat/ai/admiral/G"),
            newTransform("proxy/com/fs/starfarer/combat/ai/admiral/DeploymentManager$ReinforcementType", "com/fs/starfarer/combat/ai/admiral/G$o"),
            newTransform("FileRepository_loadImage", "o00000"),
            newTransform("FileRepository_loadSound", "Ô00000"),
            newTransform("TextureRepository_addTexture", "o00000"),
            newTransform("FontRepository_defineFont", "o00000"),
            newTransform("StarfarerSettings_getFloatValue", "ö00000"),
            newTransform("ScriptStore_getSecureClassLoader", "Object"),
            newTransform("ScriptStore_getScriptList", "Õ00000"),
            newTransform("ScriptStore_getPluginSet", "Ò00000"),
            newTransform("SpecStore_init", "ÓO0000"),
            newTransform("ResourceLocation_type", "o00000"),
            newTransform("ResourceLocation_path", "Ó00000"),
            newTransform("ResourceLoader_locationFilter", "String"),
            newTransform("ResourceLoader_withoutMods", "super"),
            newTransform("ResourceLoader_getInstance", "Object"),
            newTransform("ResourceLoader_getResourceList", "Ô00000"),
            newTransform("ResourceLocation_isMod", "Ô00000"),
            newTransform("FileUtils_loadInputStreams", "Ò00000"),
            newTransform("FileUtils_loadInputStream", "Object"),
            newTransform("FloatingTextManager_render", "o00000"),
            newTransform("ProgressBar_setDescription", "Ò00000"),
            newTransform("ProgressBar_render", "super"),
            newTransform("ProgressBar_renderWithDescription", "super"),
            newTransform("TextureHandler_getTextureID", "ö00000"),
            newTransform("TextureHandler_setPath", "o00000"),
            newTransform("TextureHandler_setHeight", "Ô00000"),
            newTransform("TextureHandler_setWidth", "Ó00000"),
            newTransform("TextureHandler_setImageHeight", "o00000"),
            newTransform("TextureHandler_setImageWidth", "new"),
            newTransform("TextureHandler_serColor1", "o00000"),
            newTransform("TextureHandler_serColor0", "Ó00000"),
            newTransform("TextureHandler_serColor2", "new"),
            newTransform("TextureTransformer_apply", "super"),
            newTransform("TextureHandler_setStringID", "new"),
            newTransform("DeploymentManager_pickReinforcement", "o00000"),
            newTransform("ScriptStore_objectRepository", "Õ00000"),
            newTransform("ScriptStore_javaSourceClassLoader", "ø00000")
    );
}
