package com.fs.starfarer.api.combat;
public enum CombatEngineLayers {
    BELOW_SHIPS_LAYER, UNDER_SHIPS_LAYER, ABOVE_SHIPS_LAYER, ABOVE_SHIPS_AND_MISSILES_LAYER,
    CONTRAILS_LAYER, ABOVE_PARTICLES_LOWER, ABOVE_PARTICLES, FF_LAYER,
    JUST_BELOW_WIDGETS, UNDER_PLANETS, PLANET_LAYER, STAR_LAYER,
    ABOVE_PLANETS, BELOW_PLANETS, ASTEROIDS_LAYER, BELOW_INDICATORS_LAYER,
    BELOW_PHASED_SHIPS_LAYER, CAPITAL_SHIPS_LAYER, CLOUD_LAYER, CRUISERS_LAYER,
    DESTROYERS_LAYER, FF_INDICATORS_LAYER, FIGHTERS_LAYER, FRIGATES_LAYER,
    PHASED_SHIPS_LAYER, STATION_WEAPONS_LAYER
}
